---

- name: KAFKA ADMIN | DOCKER | Install docker
  package:
    name: docker
    state: present

- name: KAFKA ADMIN | DOCKER | Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0755'
