---

- name: KAFKA ADMIN | DOCKER | Install docker
  package:
    name: docker
    state: present

- name: KAFKA ADMIN | DOCKER | Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0755'

- name: KAFKA ADMIN | DOCKER | Enable docker
  service:
    name: docker
    enabled: yes

- name: KAFKA ADMIN | DOCKER | Start docker
  service:
    name: docker
    state: started

- name: KAFKA ADMIN | DOCKER | Create docker-compose systemd unit
  copy:
    src: systemd/docker-compose@.service
    dest: /lib/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0755'
