---

- name: KAFKA ADMIN | KAFKA MANAGER | Ensure /etc/docker/compose/kafka-manager exists
  file:
    path: /etc/docker/compose/kafka-manager
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: KAFKA ADMIN | KAFKA MANAGER | Create docker-compose file
  copy:
    src: docker-compose/kafka-manager.yml
    dest: /etc/docker/compose/kafka-manager/docker-compose.yml
    owner: root
    group: root
    mode: '0755'

- name: KAFKA ADMIN | KAFKA MANAGER | Enable kafka-manager
  service:
    name: docker-compose@kafka-manager
    enabled: yes

- name: KAFKA ADMIN | KAFKA MANAGER | Start kafka-manager
  service:
    name: docker-compose@kafka-manager
    state: started
