---

- name: KAFKA ADMIN | KAFKA MANAGER | Ensure /etc/docker/compose/kafka-manager exists
  file:
    path: /etc/docker/compose/kafka-manager
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: KAFKA ADMIN | KAFKA MANAGER | Create docker-compose file
  template:
    src: docker-compose/kafka-manager.yml
    dest: /etc/docker/compose/kafka-manager/docker-compose.yml
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart kafka-manager

- name: KAFKA ADMIN | KAFKA MANAGER | Enable and start kafka-manager
  service:
    name: docker-compose@kafka-manager
    state: started
    enabled: yes

- name: KAFKA ADMIN | KAFKA MANAGER | Flush handlers
  meta: flush_handlers
