---

- name: KAFKA ADMIN | ZOONAVIGATOR | Ensure /etc/docker/compose/zoonavigator exists
  file:
    path: /etc/docker/compose/zoonavigator
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: KAFKA ADMIN | ZOONAVIGATOR | Create docker-compose file
  copy:
    src: docker-compose/zoonavigator.yml
    dest: /etc/docker/compose/zoonavigator/docker-compose.yml
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart zoonavigator

- name: KAFKA ADMIN | ZOONAVIGATOR | Enable and start Zoonavigator
  service:
    name: docker-compose@zoonavigator
    state: started
    enabled: yes

- name: KAFKA ADMIN | ZOONAVIGATOR | Flush handlers
  meta: flush_handlers
