# {{ ansible_managed }}
version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "{{ kafka_admin_zookeeper_hosts }}"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
